-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(AMOUNT) * p.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT p INNER JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE MONTH(o.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;
/*
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT) * P.PRICE AS TOTAL_SALES
    FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5
    GROUP BY O.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;
*/